# Generated by Django 2.2.2 on 2022-04-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200425_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='choicemu_number',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='多选题数'),
        ),
    ]
