# Generated by Django 2.2.28 on 2022-04-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_paper_choicemu_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='clazzs',
        ),
    ]
