# Generated by Django 2.2.28 on 2022-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_exam_clazzs'),
        ('user', '0009_auto_20220421_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ManyToManyField(to='user.Department', verbose_name='参加考试的部门'),
        ),
    ]
