# Generated by Django 2.2.28 on 2022-04-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_auto_20220417_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to='upload/%Y%m%d/')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('finger', models.CharField(help_text='浏览器指纹', max_length=200, verbose_name='浏览器指纹')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student')),
            ],
            options={
                'verbose_name': 'files',
                'verbose_name_plural': 'files',
                'db_table': 'tb_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
