# Generated by Django 3.2.12 on 2022-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0005_auto_20220425_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitfile',
            name='limit_random',
            field=models.IntegerField(default=1, help_text='设定上传文件列表开关', verbose_name='设定上传文件列表开关(1:开启，0:关闭)'),
            preserve_default=False,
        ),
    ]
