# Generated by Django 3.2.12 on 2022-04-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0009_auto_20220426_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomfileid',
            name='team_five',
            field=models.CharField(help_text='第五组文件id', max_length=200, verbose_name='第五组文件id'),
        ),
        migrations.AlterField(
            model_name='randomfileid',
            name='team_four',
            field=models.CharField(help_text='第四组文件id', max_length=200, verbose_name='第四组文件id'),
        ),
        migrations.AlterField(
            model_name='randomfileid',
            name='team_one',
            field=models.CharField(help_text='第一组文件id', max_length=200, verbose_name='第一组文件id'),
        ),
        migrations.AlterField(
            model_name='randomfileid',
            name='team_six',
            field=models.CharField(help_text='第六组文件id', max_length=200, verbose_name='第六组文件id'),
        ),
        migrations.AlterField(
            model_name='randomfileid',
            name='team_three',
            field=models.CharField(help_text='第三组文件id', max_length=200, verbose_name='第三组文件id'),
        ),
        migrations.AlterField(
            model_name='randomfileid',
            name='team_two',
            field=models.CharField(help_text='第二组文件id', max_length=200, verbose_name='第二组文件id'),
        ),
    ]
