# Generated by Django 3.2.12 on 2022-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0011_captainfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='captainfiles',
            name='downloadfile',
            field=models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接'),
        ),
        migrations.AddField(
            model_name='files',
            name='downloadfile',
            field=models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接'),
        ),
    ]
