# Generated by Django 3.2.12 on 2022-04-30 09:36

from django.db import migrations, models
import django.db.models.deletion
import hsoftskill.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220424_1341'),
        ('hsoftskill', '0014_examfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.judge_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '评分上传',
                'verbose_name_plural': '评分上传',
                'db_table': 'tb_judge_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
