# Generated by Django 3.2.12 on 2022-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0018_auto_20220501_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examfiles',
            name='limit_period',
        ),
        migrations.AddField(
            model_name='examfiles',
            name='exam_questions_type',
            field=models.CharField(choices=[('1', '文档'), ('2', '数通'), ('3', '服务器'), ('4', '集合')], default='4', max_length=1, verbose_name='考题类型'),
        ),
    ]
