# Generated by Django 2.2.2 on 2022-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceMu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='题目')),
                ('answer_A', models.CharField(default='', max_length=200, verbose_name='A选项')),
                ('answer_B', models.CharField(default='', max_length=200, verbose_name='B选项')),
                ('answer_C', models.CharField(default='', max_length=200, verbose_name='C选项')),
                ('answer_D', models.CharField(default='', max_length=200, verbose_name='D选项')),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='正确选项')),
                ('analysis', models.TextField(default='暂无', verbose_name='题目解析')),
                ('score', models.PositiveSmallIntegerField(default=2, verbose_name='分值')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'ordering': ['id'],
            },
        ),
    ]
