# Generated by Django 2.2.2 on 2022-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_choicemu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicemu',
            options={'ordering': ['id'], 'verbose_name': '多选题', 'verbose_name_plural': '多选题'},
        ),
        migrations.AlterField(
            model_name='choicemu',
            name='right_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=4, verbose_name='正确选项'),
        ),
    ]
