fileuserid = []
qj_userid = []
ljj_userid = []
wcl_userid = []
#csm_userid = []
lc_userid = []
ybw_userid = []
wy_userid = []
captainName = ['qiujun', 'lvjiajun','lichao','weichunlei','yaobowen','wangyang','matt', 'wangkuan', 'zhaoyang']
#downloadlink = 'http://127.0.0.1:8000'   #文件下载地址，正式环境各更改为网站后端地址
downloadlink = 'http://exam.wrlog.cn:8000'   #文件下载地址，正式环境各更改为网站后端地址