# Generated by Django 3.2.12 on 2022-05-17 16:09

from django.db import migrations, models
import django.db.models.deletion
import hsoftskill.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitFile',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('limit_period', models.IntegerField(help_text='设定考核期数', verbose_name='设定考核期数')),
                ('limit_upload', models.IntegerField(help_text='设定上传开关', verbose_name='设定上传开关(1:开启，0:关闭)')),
                ('limit_captain_upload', models.IntegerField(help_text='设定组长答题上传开关', verbose_name='设定组长答题上传开关(1:开启，0:关闭)')),
                ('limit_captain_judge', models.IntegerField(help_text='设定组长评分上传开关', verbose_name='设定组长评分上传开关(1:开启，0:关闭)')),
                ('limit_exam_upload', models.IntegerField(help_text='设定考核题上传开关', verbose_name='设定考核题上传开关(1:开启，0:关闭)')),
                ('limit_random', models.IntegerField(help_text='设定上传文件列表开关', verbose_name='设定上传文件列表开关(1:开启，0:关闭)')),
            ],
            options={
                'verbose_name': '上传限制',
                'db_table': 'tb_limit_period',
            },
        ),
        migrations.CreateModel(
            name='RandomFileId',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('team_one', models.CharField(help_text='第一组文件id', max_length=200, verbose_name='第一组文件id')),
                ('team_two', models.CharField(help_text='第二组文件id', max_length=200, verbose_name='第二组文件id')),
                ('team_three', models.CharField(help_text='第三组文件id', max_length=200, verbose_name='第三组文件id')),
                ('team_four', models.CharField(help_text='第四组文件id', max_length=200, verbose_name='第四组文件id')),
                ('team_five', models.CharField(help_text='第五组文件id', max_length=200, verbose_name='第五组文件id')),
                ('team_six', models.CharField(help_text='第六组文件id', max_length=200, verbose_name='第六组文件id')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
            ],
            options={
                'verbose_name': '随机判分组',
                'db_table': 'tb_team_random_id',
            },
        ),
        migrations.CreateModel(
            name='JudgeFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.judge_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '评分上传',
                'verbose_name_plural': '评分上传',
                'db_table': 'tb_judge_files',
                'ordering': ['upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.user_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('finger', models.CharField(help_text='浏览器指纹', max_length=200, verbose_name='浏览器指纹')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'tb_files',
                'ordering': ['upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.exam_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('exam_questions_type', models.CharField(choices=[('1', '文档'), ('2', '数通'), ('3', '服务器'), ('4', '集合')], default='4', max_length=1, verbose_name='考题类型')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '考核题发布',
                'verbose_name_plural': '考核题发布',
                'db_table': 'tb_exam_files',
                'ordering': ['upload_time'],
            },
        ),
        migrations.CreateModel(
            name='CaptainFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.captain_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('finger', models.CharField(help_text='浏览器指纹', max_length=200, verbose_name='浏览器指纹')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '组长考核文件',
                'verbose_name_plural': '组长考核文件',
                'db_table': 'tb_captain_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
