# Generated by Django 2.2.26 on 2022-04-23 11:08

from django.db import migrations, models
import django.db.models.deletion
import hsoftskill.models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitFile',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('limit_period', models.IntegerField(help_text='设定考核期数', verbose_name='设定考核期数')),
            ],
            options={
                'verbose_name': 'limit_period',
                'verbose_name_plural': 'limit_period',
                'db_table': 'tb_limit_period',
            },
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=hsoftskill.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='files',
            name='limit_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.LimitFile'),
            preserve_default=False,
        ),
    ]
