# Generated by Django 3.2.12 on 2022-06-09 11:50

from django.db import migrations, models
import django.db.models.deletion
import hsoftskill.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220517_2013'),
        ('hsoftskill', '0002_auto_20220601_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitfile',
            name='limit_random',
        ),
        migrations.AddField(
            model_name='limitfile',
            name='limit_personal_grade',
            field=models.IntegerField(default=0, help_text='个人成绩上传开关', verbose_name='个人成绩上传开关(1:开启，0:关闭)'),
        ),
        migrations.AddField(
            model_name='limitfile',
            name='limit_total_grade',
            field=models.IntegerField(default=0, help_text='总成绩上传开关', verbose_name='总成绩上传开关(1:开启，0:关闭)'),
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_captain_judge',
            field=models.IntegerField(default=0, help_text='组长评分上传开关', verbose_name='组长评分上传开关(1:开启，0:关闭)'),
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_captain_upload',
            field=models.IntegerField(default=0, help_text='组长答题上传开关', verbose_name='组长答题上传开关(1:开启，0:关闭)'),
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_exam_upload',
            field=models.IntegerField(default=0, help_text='考核题上传开关', verbose_name='考核题上传开关(1:开启，0:关闭)'),
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_period',
            field=models.IntegerField(help_text='设定考核期数', verbose_name='考核期数'),
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_upload',
            field=models.IntegerField(default=0, help_text='设定上传开关', verbose_name='上传开关(1:开启，0:关闭)'),
        ),
        migrations.CreateModel(
            name='PersonalGradeFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.personalgrade_directory_path)),
                ('downloadfile', models.CharField(blank=True, help_text='下载链接', max_length=200, null=True, verbose_name='下载链接')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '个人成绩文件',
                'verbose_name_plural': '个人成绩文件',
                'db_table': 'tb_personal_grade_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
