# Generated by Django 3.2.12 on 2022-04-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0002_auto_20220423_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limitfile',
            options={},
        ),
    ]
