# Generated by Django 3.2.12 on 2022-04-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0004_limitfile_limit_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['upload_time'], 'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
        migrations.AlterModelOptions(
            name='limitfile',
            options={'verbose_name': '上传限制'},
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_upload',
            field=models.IntegerField(help_text='设定上传开关', verbose_name='设定上传开关(1:开启，0:关闭)'),
        ),
    ]
