# Generated by Django 3.2.12 on 2023-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0005_linuxscore10_score10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score10',
            name='period',
            field=models.IntegerField(default=10, verbose_name='考核期数'),
        ),
    ]
