# Generated by Django 3.2.12 on 2023-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0006_alter_score10_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScore11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('period', models.IntegerField(default=11, verbose_name='考核期数')),
                ('team', models.CharField(max_length=100, verbose_name='小组')),
                ('item1', models.FloatField(blank=True, null=True, verbose_name='按要求配置路由协议（10分）')),
                ('item2', models.FloatField(blank=True, null=True, verbose_name='按要求配置IP地址（10分）')),
                ('item3', models.FloatField(blank=True, null=True, verbose_name='解决客户端获取不到IP地址问题(20分)')),
                ('item4', models.FloatField(blank=True, null=True, verbose_name='客户端按要求获取指定IP地址(20分)')),
                ('item5', models.FloatField(blank=True, null=True, verbose_name='AR4/AR8 链路及chap认证正确，并使用本人姓名作为用户名密码，链路状态正常(10分')),
                ('item6', models.FloatField(blank=True, null=True, verbose_name='10段、20段可以访问OA Service，70段、80段可以访问Mail Service(20分)')),
                ('item7', models.FloatField(blank=True, null=True, verbose_name='其余网段不可访问非允许服务(10分)')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总分')),
            ],
            options={
                'verbose_name': '数通成绩11',
                'verbose_name_plural': '数通成绩11',
                'db_table': 'exam_score_network_11',
                'unique_together': {('name', 'period')},
            },
        ),
    ]
