# Generated by Django 3.2.12 on 2022-04-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0006_limitfile_limit_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFileId',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('team_one', models.CharField(help_text='第一组文件id', max_length=200, verbose_name='第一组文件id')),
                ('team_two', models.CharField(help_text='第二组文件id', max_length=200, verbose_name='第二组文件id')),
                ('team_three', models.CharField(help_text='第三组文件id', max_length=200, verbose_name='第三组文件id')),
                ('team_four', models.CharField(help_text='第四组文件id', max_length=200, verbose_name='第四组文件id')),
                ('team_five', models.CharField(help_text='第五组文件id', max_length=200, verbose_name='第五组文件id')),
                ('team_six', models.CharField(help_text='第六组文件id', max_length=200, verbose_name='第六组文件id')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
            ],
            options={
                'verbose_name': '随机判分组',
                'db_table': 'tb_teamrandomid',
            },
        ),
    ]
