# Generated by Django 3.2.12 on 2023-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0007_networkscore11'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxScore12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('period', models.IntegerField(default=12, verbose_name='考核期数')),
                ('team', models.CharField(max_length=100, verbose_name='小组')),
                ('item1', models.FloatField(blank=True, null=True, verbose_name='安装并启动httpd服务(10分)')),
                ('item2', models.FloatField(blank=True, null=True, verbose_name='开机自启动httpd服务(10分)')),
                ('item3', models.FloatField(blank=True, null=True, verbose_name='创建虚拟主机配置文件(10分)')),
                ('item4', models.FloatField(blank=True, null=True, verbose_name='设置虚拟主机目录、端口(10分)')),
                ('item5', models.FloatField(blank=True, null=True, verbose_name='设置虚拟主机权限(15分)')),
                ('item6', models.FloatField(blank=True, null=True, verbose_name='设置虚拟主机日志(15分)')),
                ('item7', models.FloatField(blank=True, null=True, verbose_name='设置虚拟主机域名及权限(30分)')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总分')),
            ],
            options={
                'verbose_name': '服务器成绩12',
                'verbose_name_plural': '服务器成绩12',
                'db_table': 'exam_score_linux_12',
                'unique_together': {('name', 'period')},
            },
        ),
    ]
