# Generated by Django 3.2.12 on 2022-04-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0007_randomfileid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='randomfileid',
            table='tb_team_random_id',
        ),
    ]
