# Generated by Django 3.2.12 on 2023-06-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0009_score_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinuxScore10',
        ),
        migrations.DeleteModel(
            name='LinuxScore12',
        ),
        migrations.DeleteModel(
            name='LinuxScore3',
        ),
        migrations.DeleteModel(
            name='LinuxScore4',
        ),
        migrations.DeleteModel(
            name='LinuxScore5',
        ),
        migrations.DeleteModel(
            name='LinuxScore6',
        ),
        migrations.DeleteModel(
            name='LinuxScore7',
        ),
        migrations.DeleteModel(
            name='LinuxScore8',
        ),
        migrations.DeleteModel(
            name='LinuxScore9',
        ),
        migrations.DeleteModel(
            name='NetworkScore11',
        ),
        migrations.DeleteModel(
            name='NetworkScore3',
        ),
        migrations.DeleteModel(
            name='NetworkScore4',
        ),
        migrations.DeleteModel(
            name='NetworkScore5',
        ),
        migrations.DeleteModel(
            name='NetworkScore6',
        ),
        migrations.DeleteModel(
            name='NetworkScore7',
        ),
        migrations.DeleteModel(
            name='NetworkScore8',
        ),
        migrations.DeleteModel(
            name='NetworkScore9',
        ),
        migrations.DeleteModel(
            name='OfficeScore3',
        ),
        migrations.DeleteModel(
            name='OfficeScore4',
        ),
        migrations.DeleteModel(
            name='OfficeScore5',
        ),
        migrations.DeleteModel(
            name='Score10',
        ),
        migrations.DeleteModel(
            name='Score3',
        ),
        migrations.DeleteModel(
            name='Score4',
        ),
        migrations.DeleteModel(
            name='Score5',
        ),
        migrations.DeleteModel(
            name='Score6',
        ),
        migrations.DeleteModel(
            name='Score7',
        ),
        migrations.DeleteModel(
            name='Score8',
        ),
        migrations.DeleteModel(
            name='Score9',
        ),
    ]
