# Generated by Django 3.2.12 on 2022-04-27 18:22

from django.db import migrations, models
import django.db.models.deletion
import hsoftskill.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220424_1341'),
        ('hsoftskill', '0010_auto_20220426_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainFiles',
            fields=[
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('name', models.CharField(help_text='文件名称', max_length=200, verbose_name='文件名称')),
                ('period', models.IntegerField(help_text='考核期数', verbose_name='考核期数')),
                ('file', models.FileField(upload_to=hsoftskill.models.captain_directory_path)),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('finger', models.CharField(help_text='浏览器指纹', max_length=200, verbose_name='浏览器指纹')),
                ('limit_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'verbose_name': '组长考核文件',
                'verbose_name_plural': '组长考核文件',
                'db_table': 'tb_captain_files',
                'ordering': ['upload_time'],
            },
        ),
    ]
