# Generated by Django 3.2.12 on 2022-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0012_auto_20220427_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitfile',
            name='limit_captain_upload',
            field=models.IntegerField(default=1, help_text='设定组长上传开关', verbose_name='设定组长上传开关(1:开启，0:关闭)'),
            preserve_default=False,
        ),
    ]
