# Generated by Django 3.2.12 on 2022-04-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0015_judgefiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfiles',
            name='limit_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hsoftskill.limitfile'),
        ),
        migrations.AlterField(
            model_name='examfiles',
            name='period',
            field=models.IntegerField(help_text='考核期数', verbose_name='考核期数'),
        ),
    ]
