# Generated by Django 3.2.12 on 2022-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0016_auto_20220430_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitfile',
            name='limit_exam_upload',
            field=models.IntegerField(default=1, help_text='设定考核题上传开关', verbose_name='设定考核题上传开关(1:开启，0:关闭)'),
            preserve_default=False,
        ),
    ]
