# Generated by Django 3.2.12 on 2022-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsoftskill', '0017_limitfile_limit_exam_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitfile',
            name='limit_captain_judge',
            field=models.IntegerField(default=1, help_text='设定组长评分上传开关', verbose_name='设定组长评分上传开关(1:开启，0:关闭)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limitfile',
            name='limit_captain_upload',
            field=models.IntegerField(help_text='设定组长答题上传开关', verbose_name='设定组长答题上传开关(1:开启，0:关闭)'),
        ),
    ]
