# Generated by Django 3.2.12 on 2022-05-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('user', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_answer', models.TextField(blank=True, null=True, verbose_name='你的作答')),
                ('cmd_msg', models.TextField(blank=True, null=True, verbose_name='输出结果')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practice', verbose_name='练习')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.program', verbose_name='编程题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '编程题答题记录',
                'verbose_name_plural': '编程题答题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_answer', models.TextField(blank=True, null=True, verbose_name='你的作答')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.judge', verbose_name='判断题')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practice', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '判断题答题记录',
                'verbose_name_plural': '判断题答题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_answer', models.TextField(blank=True, null=True, verbose_name='你的作答')),
                ('fill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.fill', verbose_name='填空题')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practice', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '填空题答题记录',
                'verbose_name_plural': '填空题答题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_answer', models.TextField(blank=True, null=True, verbose_name='你的作答')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choice', verbose_name='单选题')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practice', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '单选题答题记录',
                'verbose_name_plural': '单选题答题记录',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceMuRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_answer', models.TextField(blank=True, null=True, verbose_name='你的作答')),
                ('choicemu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.choicemu', verbose_name='多选题')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.practice', verbose_name='练习')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '多选题答题记录',
                'verbose_name_plural': '多选题答题记录',
                'ordering': ['id'],
            },
        ),
    ]
