# Generated by Django 2.2.2 on 2022-04-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20220417_1420'),
        ('record', '0005_auto_20220417_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemurecord',
            name='choice',
        ),
        migrations.AddField(
            model_name='choicemurecord',
            name='choicemu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.ChoiceMu', verbose_name='多选题'),
            preserve_default=False,
        ),
    ]
