# Generated by Django 3.2.12 on 2022-05-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='工程部', max_length=20, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=20, verbose_name='路径')),
                ('component', models.CharField(default='Layout', max_length=20, verbose_name='组件')),
                ('alwaysShow', models.BooleanField(verbose_name='显示权限')),
                ('name', models.CharField(default='', max_length=20, verbose_name='菜单名称')),
            ],
            options={
                'verbose_name': '菜单权限信息',
                'verbose_name_plural': '菜单权限信息',
                'db_table': 'user_menu',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetaChildrenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('icon', models.CharField(default='', max_length=20, verbose_name='图标')),
            ],
            options={
                'verbose_name': '子菜单元信息',
                'verbose_name_plural': '子菜单元信息',
                'db_table': 'user_meta_children',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, verbose_name='标题')),
                ('icon', models.CharField(default='', max_length=20, verbose_name='图标')),
            ],
            options={
                'verbose_name': '菜单元信息',
                'verbose_name_plural': '菜单元信息',
                'db_table': 'user_meta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.menuinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=1, verbose_name='性别')),
                ('avatar', models.CharField(default='', max_length=20, verbose_name='头像')),
                ('introduction', models.CharField(default='', max_length=20, verbose_name='介绍')),
                ('department', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department', verbose_name='部门')),
                ('menuroles', models.ManyToManyField(blank=True, through='user.StaffMenu', to='user.MenuInfo', verbose_name='用户菜单关系')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'user_student',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRolesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='权限名称')),
                ('roles_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='user.student', verbose_name='权限信息')),
            ],
            options={
                'verbose_name': '权限信息',
                'verbose_name_plural': '权限信息',
                'db_table': 'user_roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserLayoutRolesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='权限名称')),
                ('roles_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='user.metainfo', verbose_name='权限信息')),
            ],
            options={
                'verbose_name': 'layout菜单按钮权限信息',
                'verbose_name_plural': 'layout菜单按钮权限信息',
                'db_table': 'user_layout_roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别')),
                ('title', models.CharField(choices=[('审批员', '审批员')], default='审批员', max_length=5, verbose_name='角色')),
                ('institute', models.CharField(default='', max_length=20, verbose_name='项目组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '审批员',
                'verbose_name_plural': '审批员',
                'db_table': 'user_teacher',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='staffmenu',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
        migrations.CreateModel(
            name='RolesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys', models.CharField(default='', max_length=20, verbose_name='权限名称')),
                ('roles_meta_children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='user.metachildreninfo', verbose_name='权限信息')),
            ],
            options={
                'verbose_name': '子菜单按钮权限信息',
                'verbose_name_plural': '子菜单按钮权限信息',
                'db_table': 'user_children_roles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='menuinfo',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metainfo', to='user.metainfo', verbose_name='元信息'),
        ),
        migrations.CreateModel(
            name='MenuChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=20, verbose_name='路径')),
                ('component', models.CharField(default='Layout', max_length=20, verbose_name='组件')),
                ('alwaysShow', models.BooleanField(verbose_name='显示权限')),
                ('name', models.CharField(default='', max_length=20, verbose_name='菜单名称')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.menuinfo', verbose_name='菜单信息')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.metachildreninfo', verbose_name='=子菜单元信息')),
            ],
            options={
                'verbose_name': '子菜单信息',
                'verbose_name_plural': '子菜单信息',
                'db_table': 'user_menu_children',
                'ordering': ['id'],
            },
        ),
    ]
