# Generated by Django 3.2.12 on 2023-03-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220517_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuinfo',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='rolesinfo',
            name='roles_meta_children',
        ),
        migrations.RemoveField(
            model_name='staffmenu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='staffmenu',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='userlayoutrolesinfo',
            name='roles_meta',
        ),
        migrations.RemoveField(
            model_name='student',
            name='menuroles',
        ),
        migrations.DeleteModel(
            name='MenuChildren',
        ),
        migrations.DeleteModel(
            name='MenuInfo',
        ),
        migrations.DeleteModel(
            name='MetaChildrenInfo',
        ),
        migrations.DeleteModel(
            name='MetaInfo',
        ),
        migrations.DeleteModel(
            name='RolesInfo',
        ),
        migrations.DeleteModel(
            name='StaffMenu',
        ),
        migrations.DeleteModel(
            name='UserLayoutRolesInfo',
        ),
    ]
