# Generated by Django 2.2.2 on 2022-04-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200425_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='clazz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.Clazz', verbose_name='班级'),
        ),
    ]
