# Generated by Django 2.2.28 on 2022-04-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_remove_exam_clazzs'),
        ('user', '0008_auto_20220417_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='年级')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('department', models.CharField(max_length=20, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='clazz',
        ),
        migrations.DeleteModel(
            name='Clazz',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='部门'),
        ),
    ]
