# Generated by Django 2.2.28 on 2022-04-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220421_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='major',
        ),
        migrations.RemoveField(
            model_name='department',
            name='year',
        ),
    ]
