# Generated by Django 3.2.12 on 2022-04-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220421_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
