# Generated by Django 3.2.12 on 2022-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': '审批员', 'verbose_name_plural': '审批员'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default='', max_length=20, verbose_name='项目组'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('审批员', '审批员')], default='审批员', max_length=5, verbose_name='角色'),
        ),
    ]
